crawler:
  search_url: 'https://www.google.com/search?tbs=sur:fmc&tbm=isch&q='
  selector: '#isr_mc .rg_meta'
  attribute: 'ou'
  referer: 'https://www.google.com'
  user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36'
